# Generated by Django 4.0.6 on 2022-07-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('MemberId', models.AutoField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(max_length=100)),
                ('Panel', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('PanelId', models.AutoField(primary_key=True, serialize=False)),
                ('PanelName', models.CharField(max_length=100)),
            ],
        ),
    ]
